import { BASE_URL } from "@/config/env";
import { Certificate } from "@/types";

const CERTIFICATES: Certificate[] = [
    {
        courseLink:
            "https://www.udemy.com/share/10dasB3@X0vZ9F0id4qBL8y2SkOwozeRxp70GD7JWR9cWmjIqnpnf4Efp_JSbUjtitd5gB9yfg==",
        name: "Agentic AI Engineering",
        dateCompleted: new Date("2025-06-12"),
        status: "completed",
        platform: "Udemy",
        platformLogo: `${BASE_URL}/images/certificates/udemy-logo.png`,
        skills: [
            "AI Agents",
            "OpenAI Agents SDK",
            "CrewAI",
            "MCP",
            "LangGraph",
            "Multi-Agent Systems",
            "Autonomous Workflows",
            "Python",
        ],
        provider: "Ed Donner - Ligency Team",
        certificateImage: `${BASE_URL}/images/certificates/ai-engineering-certificate.jpg`,
        certificateLink:
            "https://www.udemy.com/certificate/UC-040b9e0b-c8ff-4b47-a1e3-893e80c7ca04",
    },
    {
        courseLink:
            "https://www.udemy.com/share/10bOXH3@2gFWjrfB2kscaF1cPlZCL6m_QrMZDFPf_BnNF18QGpwoEMHzRPKaLt3WW15F3eqfFw==",
        name: "LLM Engineering",
        platform: "Udemy",
        dateCompleted: new Date("2025-05-07"),
        platformLogo: `${BASE_URL}/images/certificates/udemy-logo.png`,
        certificateLink:
            "https://www.udemy.com/certificate/UC-e1862b94-8f6f-4ba0-8d05-bf0a2023920a",
        certificateImage: `${BASE_URL}/images/certificates/llm-certificate.jpg`,
        status: "completed",
        skills: [
            "Prompt Engineering",
            "Vector DB",
            "Python",
            "RAG",
            "Gradio",
            "Fine-tuning",
            "Hugging Face",
        ],
        provider: "Ed Donner - Ligency Team",
    },
    {
        courseLink:
            "https://www.udemy.com/share/10dgIV3@3PRRW6hZhNZus-WqMJ7klaYzQ9JrqFTfSFMdJ8Lcsuf7x7MZZLXElzSgY4pgXSsuJQ==",
        name: "AI Agents & Autonomous Apps with LangGraph & LangChain",
        platform: "Udemy",
        platformLogo: `${BASE_URL}/images/certificates/udemy-logo.png`,
        status: "ongoing",
        skills: [
            "LangGraph",
            "LangChain",
            "AI Agents",
            "Multi-Agent Systems",
            "Autonomous Workflows",
            "Python",
        ],
        provider: "Krish Naik - KRISHAI Technologies Private Limited",
    },
    {
        courseLink:
            "https://www.udemy.com/share/104Tz63@7P1To3EQcAXMXxYDRpGYDQbhoUKPzgjok3XU6cJRKaSrO5RGltZ_dGX2tAKtAv5UCw==",
        name: "DevOps Beginners to Advanced with Projects",
        platform: "Udemy",
        dateCompleted: new Date("2025-05-31"),
        platformLogo: `${BASE_URL}/images/certificates/udemy-logo.png`,
        certificateLink:
            "https://www.udemy.com/certificate/UC-0f82967f-c0f2-4abf-a24b-7486388a0d21/",
        certificateImage: `${BASE_URL}/images/certificates/devops-certificate.jpg`,
        status: "completed",
        skills: [
            "AWS",
            "Linux",
            "Scripting",
            "Docker",
            "Kubernetes",
            "CI/CD",
            "Terraform",
            "GitOps",
            "Python",
        ],
        provider: "Imran Teli",
    },
    // {
    //     courseLink:
    //         "https://www.udemy.com/share/104coM3@xjybR_4oh_OZZY-lNCA-qu-ewROtCKizj60DXcb9NcOc8-lswhFP4w2FGQeh_5NEjw==",
    //     name: "Next.js 15 & React - The Complete Guide",
    //     platform: "Udemy",
    //     platformLogo: `${BASE_URL}/images/certificates/udemy-logo.png`,
    //     status: "plan",
    //     skills: [
    //         "Next.js 15",
    //         "React",
    //         "SSR",
    //         "SSG",
    //         "Pre-rendering",
    //         "App Router",
    //         "Authentication",
    //     ],
    //     provider: "Maximilian Schwarzmüller",
    // },
    {
        courseLink:
            "https://www.udemy.com/share/102VKE3@1hH-HBkaDluXZ2E3EW-PYqh7Bb4REBT2tXJBVqzCJ6QEtEUhecWr5S578p6FyI1mZg==",
        name: "Microservices with Node JS and React",
        platform: "Udemy",
        dateCompleted: new Date("2025-06-25"),
        platformLogo: `${BASE_URL}/images/certificates/udemy-logo.png`,
        status: "completed",
        skills: [
            "Node.js",
            "Express JS",
            "Jest",
            "Typescript",
            "Microservices",
            "MongoDB",
            "Docker",
            "Kubernetes",
            "Event-Driven Architecture",
        ],
        provider: "Stephen Grider",
        certificateLink:
            "https://www.udemy.com/certificate/UC-6e9483a6-4a39-46b5-b659-5acb8681c5e4",
        certificateImage: `${BASE_URL}/images/certificates/nodejs-microservices-certificate.jpg`,
    },
    {
        courseLink:
            "https://www.udemy.com/share/1013ja3@oS043JFY0UNL77HWc8_rGbaD2kvGKWfUbI-lhoJMmag0RyTNm8TvvgtboAGX66L3kQ==",
        name: "Data Structures + Algorithms",
        platform: "Udemy",
        dateCompleted: new Date("2025-07-15"),
        platformLogo: `${BASE_URL}/images/certificates/udemy-logo.png`,
        status: "completed",
        skills: [
            "Big O",
            "Algorithms",
            "Sorting",
            "BFS + DFS (Searching)",
            "Recursion",
            "Dynamic Programming",
            "Data Structures",
            "Arrays",
            "Queues",
            "Graph",
            "Hash Tables",
            "Trees",
            "Linked Lists",
            "Stacks",
        ],
        provider: "Andrei Neagoie",
        certificateLink:
            "https://www.udemy.com/certificate/UC-ab72d5ec-6197-4e2d-895a-2f4c0bc3f909",
        certificateImage: `${BASE_URL}/images/certificates/data-structures-and-algorithms-certificate.jpg`,
    },
    {
        courseLink:
            "https://www.udemy.com/share/101WaI3@55Afd-hgRS9bCh7He9zYyvLm4Wm8EIZFuiBK3RIiQLqTEhB8FOyc5HaUaPYpzkdTdw==",
        name: "Learn Ethical Hacking From Scratch",
        platform: "Udemy",
        platformLogo: `${BASE_URL}/images/certificates/udemy-logo.png`,
        status: "plan",
        skills: [
            "Ethical Hacking",
            "Penetration Testing",
            "Network Security",
            "Web Application Security",
            "kaliLinux",
        ],
        provider: "Zaid Sabih - z Security",
    },
    {
        name: "Rest API (Intermediate)",
        platform: "Hacker Rank",
        dateCompleted: new Date("2025-07-25"),
        platformLogo: `${BASE_URL}/images/certificates/hackerrank-logo.png`,
        status: "completed",
        skills: ["Rest API"],
        provider: "HackerRank - Harishankaran K",
        certificateImage: `${BASE_URL}/images/certificates/rest-api-certificate.png`,
        certificateLink:
            "https://www.hackerrank.com/certificates/iframe/be46e592f781",
    },
    {
        name: "React.js",
        platform: "Hacker Rank",
        dateCompleted: new Date("2025-07-23"),
        platformLogo: `${BASE_URL}/images/certificates/hackerrank-logo.png`,
        status: "completed",
        skills: ["React.js"],
        provider: "HackerRank - Harishankaran K",
        certificateImage: `${BASE_URL}/images/certificates/react-certificate.png`,
        certificateLink:
            "https://www.hackerrank.com/certificates/iframe/3051c3c96b0d",
    },
    {
        name: "Node.js (Basic)",
        platform: "Hacker Rank",
        dateCompleted: new Date("2025-07-23"),
        platformLogo: `${BASE_URL}/images/certificates/hackerrank-logo.png`,
        status: "completed",
        skills: ["Node.js"],
        provider: "HackerRank - Harishankaran K",
        certificateImage: `${BASE_URL}/images/certificates/nodejs-certificate.png`,
        certificateLink:
            "https://www.hackerrank.com/certificates/iframe/b952380c52ba",
    },
    {
        name: "JavaScript (Intermediate)",
        platform: "Hacker Rank",
        dateCompleted: new Date("2025-07-24"),
        platformLogo: `${BASE_URL}/images/certificates/hackerrank-logo.png`,
        status: "completed",
        skills: ["Javascript"],
        provider: "HackerRank - Harishankaran K",
        certificateImage: `${BASE_URL}/images/certificates/javascript-intermediate-certificate.png`,
        certificateLink:
            "https://www.hackerrank.com/certificates/iframe/29f9c9cf5ed8",
    },
    {
        name: "JavaScript (Basic)",
        platform: "Hacker Rank",
        dateCompleted: new Date("2025-07-24"),
        platformLogo: `${BASE_URL}/images/certificates/hackerrank-logo.png`,
        status: "completed",
        skills: ["Javascript"],
        provider: "HackerRank - Harishankaran K",
        certificateImage: `${BASE_URL}/images/certificates/javascript-basic-certificate.png`,
        certificateLink:
            "https://www.hackerrank.com/certificates/iframe/f53f89b7aa52",
    },
    {
        name: "Python (Basic)",
        platform: "Hacker Rank",
        dateCompleted: new Date("2025-07-25"),
        platformLogo: `${BASE_URL}/images/certificates/hackerrank-logo.png`,
        status: "completed",
        skills: ["Python"],
        provider: "HackerRank - Harishankaran K",
        certificateImage: `${BASE_URL}/images/certificates/python-basic-certificate.png`,
        certificateLink:
            "https://www.hackerrank.com/certificates/iframe/2aba302a9651",
    },
    {
        name: "SQL (Intermediate)",
        platform: "Hacker Rank",
        dateCompleted: new Date("2025-07-26"),
        platformLogo: `${BASE_URL}/images/certificates/hackerrank-logo.png`,
        status: "completed",
        skills: ["Python"],
        provider: "HackerRank - Harishankaran K",
        certificateImage: `${BASE_URL}/images/certificates/sql-intermediate-certificate.png`,
        certificateLink:
            "https://www.hackerrank.com/certificates/iframe/1653a96f44dc",
    },
    {
        name: "SQL (Basic)",
        platform: "Hacker Rank",
        dateCompleted: new Date("2025-07-25"),
        platformLogo: `${BASE_URL}/images/certificates/hackerrank-logo.png`,
        status: "completed",
        skills: ["Python"],
        provider: "HackerRank - Harishankaran K",
        certificateImage: `${BASE_URL}/images/certificates/sql-basic-certificate.png`,
        certificateLink:
            "https://www.hackerrank.com/certificates/iframe/395a298b448c",
    },
    {
        name: "PostgreSQL",
        platform: "SimpliLearn",
        dateCompleted: new Date("2025-07-26"),
        platformLogo: `${BASE_URL}/images/certificates/simplilearn-logo.png`,
        status: "completed",
        skills: ["PostgreSQL"],
        provider: "SimpliLearn - Krishna Kumar",
        certificateImage: `${BASE_URL}/images/certificates/postgresql-certificate.png`,
        certificateLink:
            "https://certificates.simplicdn.net/share/8687500_90642931753510996163.pdf",
    },
    {
        name: "Basic of SaaS",
        platform: "SimpliLearn",
        dateCompleted: new Date("2025-07-27"),
        platformLogo: `${BASE_URL}/images/certificates/simplilearn-logo.png`,
        status: "completed",
        skills: ["SaaS"],
        provider: "SimpliLearn - Krishna Kumar",
        certificateImage: `${BASE_URL}/images/certificates/basic-saas-certificate.png`,
        certificateLink:
            "https://certificates.simplicdn.net/share/8688983_90642931753528496051.pdf",
    },
];

export default CERTIFICATES;
